language: node_js
install: npm install git+https://github.com/davidascher/gitbook.git#webmaker-styling
before_script: gitbook install
node_js:
- '0.10'
script: gitbook build
deploy:
  provider: s3
  access_key_id: AKIAIPO3ZPOF7CHX3IHA
  secret_access_key:
    secure: sgb8IjbH0UkoONe1NS1h5QdUZ3RANSC3tre2Xqf7xbXZLiW8K2Hn8K6WJiVJ1w1NN+XErW8lpSq5O4HmzHk2L+CHCGisEP3FVPzI0WfgdjS4Ab3kI90irmepdFkgxIBBcil5RJiKpk88qH4cHm1O8mO1YPnzQPwya34YSynb5EQ=
  bucket: mozilla-academy-strategy
  local-dir: _book
  acl: public_read
  on:
    repo: MozillaFoundation/strategy
  bucket: mozilla-academy-strategy
  acl: public_read
  skip_cleanup: true
  endpoint: mozilla-academy-strategy.s3-website-us-east-1.amazonaws.com
  local_dir: _book
sudo: required

