language: node_js
install: npm install git+https://github.com/davidascher/gitbook.git#webmaker-styling && npm install surge
before_script: gitbook install
node_js:
- '0.10'
script: gitbook build
sudo: required
surge:
  login: da@mozillafoundation.org
  token:
    secure: Xa81lTZ8Fhux917zucK4z8/c/oRfsgoOEs8l8ggdalvV3watJ4EyeLkGdSeTzM7FC3avf7ffuLh105ew8D7CnJaqMfcObxaCEH8NmKL36Qt6ff+XtMvkGdVkmrJnrvN9iYKYqwHZHWzzfZE1WZLgL4G8Q7CFilIbfah2c6UgdjI=
after_script:
  surge -d mozilla-academy-strategy -p _book
